version: '3.3'
services: 
    config-server:
        image: config-server:v2
        ports:
           - "8888:8888"
        restart: always
        networks: 
            - springcloud
    servicio-eureka-server:
        image: servicio-eureka-server:v1
        ports:
           - "8761:8761"
        restart: always
        networks: 
            - springcloud 
    ms-mysql5:
        image: mysql:5.7.28 
        ports:
            - "3306:3306"
        restart: always
        networks: 
            - springcloud
        environment: 
            - MYSQL_DATABASE:db_springboot_cloud
            - MYSQL_ROOT_PASSWORD:root
    ms-postgres12:
        image: postgres:12-alpine
        ports:
            - "5432:5432"
        restart: always
        networks:
            - springcloud
        environment: 
            POSTGRES_DB: db_springboot_cloud
            POSTGRES_PASSWORD: root
    servicio-productos:
        image: servicio-productos:v1
        restart: always
        networks:
            - springcloud
        depends_on: 
            - config-server
            - servicio-eureka-server
            - ms-mysql5
    servicio-items:
        image: servicio-items:v1
        ports:
            - "8002:8002"
            - "8005:8005"
            - "8007:8007"
        restart: always
        networks:
            - springcloud
        depends_on: 
            - config-server
            - servicio-eureka-server
            - servicio-productos
    servicio-usuarios:
        image: servicio-usuarios:v1
        restart: always
        networks:
            - springcloud
        depends_on: 
            - config-server
            - servicio-eureka-server
            - ms-postgres12
    servicio-oauth:
        image: servicio-oauth:v1
        ports:
            - "9100:9100"
        restart: always
        networks:
            - springcloud
        depends_on: 
            - config-server
            - servicio-eureka-server
            - servicio-usuarios
    servicio-zuul-server:
        image: servicio-zuul-server:v1
        ports:
            - "8090:8090"
        restart: always
        networks:
            - springcloud
        depends_on: 
            - config-server
            - servicio-eureka-server
            - servicio-productos
            - servicio-items
            - servicio-usuarios
            - servicio-oauth
    ms-rabbitmq38:
        image: rabbitmq:3.8-management-alpine
        ports:
            - "15672:15672"
            - "5672:5672"
        restart: always
        networks:
            - springcloud
    zipkin-server:
        image: zipkin-server:v1
        ports:
            - "9411:9411"
        restart: always
        networks:
            - springcloud
        depends_on: 
            - ms-rabbitmq38
            - ms-mysql5
        environment: 
            RABBIT_ADDRESSES: ms-rabbitmq38:5672
            STORAGE_TYPE: mysql
            MYSQL_USER: zipkin
            MYSQL_PASS: zipkin
            MYSQL_HOST: ms-mysql5
networks: 
    springcloud: